# Generated by Django 2.0 on 2022-05-19 15:11

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tags', models.CharField(max_length=255, null=True)),
                ('content', mdeditor.fields.MDTextField()),
                ('title', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('state', models.IntegerField(default=0)),
                ('read_num', models.IntegerField(default=0)),
                ('back_info', models.TextField(default='')),
                ('type', models.IntegerField(default=0)),
                ('article_link', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareplat.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('file_size', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Update_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('content', mdeditor.fields.MDTextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('is_lock', models.BooleanField(default=False)),
                ('login_fail', models.IntegerField(default=0)),
                ('invitation_code', models.CharField(max_length=255, null=True, unique=True)),
                ('invitation_user', models.IntegerField(null=True)),
                ('create_time', models.DateTimeField()),
                ('invitation_num', models.IntegerField(default=0)),
                ('article_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='tool',
            name='upload_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shareplat.User'),
        ),
        migrations.AddField(
            model_name='collect',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareplat.User'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shareplat.User'),
        ),
        migrations.AddField(
            model_name='article',
            name='classify',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shareplat.Classify'),
        ),
    ]
