# Generated by Django 2.0 on 2022-05-21 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareplat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='invitation_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='invitation_num',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_lock',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login_fail',
        ),
    ]
